# Generated by Django 4.1.4 on 2022-12-27 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='poste',
            old_name='created_at',
            new_name='reated_at',
        ),
        migrations.AddField(
            model_name='poste',
            name='ccategory',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app_name.category'),
            preserve_default=False,
        ),
    ]
