# Generated by Django 4.1.4 on 2022-12-27 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0002_category_rename_created_at_poste_reated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poste',
            old_name='ccategory',
            new_name='category',
        ),
    ]
