# Generated by Django 4.1.4 on 2022-12-27 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0003_rename_ccategory_poste_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poste',
            new_name='Post',
        ),
    ]
